# Generated by Django 5.2.13 on 2026-05-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tree",
            name="ai_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tree",
            name="is_dangerous",
            field=models.BooleanField(default=False),
        ),
    ]
