# Generated by Django 6.0.5 on 2026-05-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_tree_ai_description_tree_is_dangerous'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='ai_vision_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
