# Generated by Django 5.2.13 on 2026-05-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wind_speed", models.FloatField()),
                ("precipitation", models.FloatField()),
                ("date", models.DateField()),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
