# Generated by Django 6.0.5 on 2026-05-06 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_tree_ai_vision_score'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_speed', models.FloatField()),
                ('wind_gust', models.FloatField(blank=True, null=True)),
                ('precipitation', models.FloatField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('storm_indicator', models.BooleanField(default=False)),
                ('forecast_max_wind_24h', models.FloatField(blank=True, null=True)),
                ('weather_code', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshots', to='trees.tree')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
